### ISSUE TITLE
Exception when assigning a value to an already assigned constant

### ISSUE THREAD

**Issue by manlanger** [stefan-rass/sunset-ffapl#6]
Given the following FFapl code:

program calculate{
               const a: Integer := 2;
               a := 5;
}

Leads to the following exception (instead of an error):

Exception in thread "Thread-0" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key 201
               at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
               at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:558)
               at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
               at ffapl.utils.FFaplProperties.getProperty(FFaplProperties.java:29)
               at ffapl.utils.FFaplProperties.getProperty(FFaplProperties.java:41)
               at ffapl.exception.FFaplException.<init>(FFaplException.java:49)
               at ffapl.exception.FFaplException.<init>(FFaplException.java:66)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:245)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.ASTAssignment.accept(ASTAssignment.java:72)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1862)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.FFaplNodeChoice.accept(FFaplNodeChoice.java:102)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1644)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.ASTStatement.accept(ASTStatement.java:62)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1913)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.FFaplNodeSequence.accept(FFaplNodeSequence.java:54)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1862)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.FFaplNodeChoice.accept(FFaplNodeChoice.java:102)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1888)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.FFaplNodeListOpt.accept(FFaplNodeListOpt.java:53)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1664)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:115)
               at ffapl.ast.nodes.ASTStatementList.accept(ASTStatementList.java:62)
               at ffapl.visitor.FFaplSymbolTypeCheckingVisitor.visit(FFaplSymbolTypeCheckingVisitor.java:1328)
               at ffapl.FFaplInterpreter.run(FFaplInterpreter.java:71)

**Comment by manlanger** [comment]
According error code (201) was missing in en-bundle.
